name: Build & WebDeploy Autentication (.NET 8)

on:
  push:
    branches: [ master, main ]
  workflow_dispatch: {}

jobs:
  build_and_deploy_backend:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore

      # 1) Publica SOLO Autentication.Web (framework-dependent)
      - name: Publish (Release)
        run: dotnet publish ./Autentication/Autentication.Web.csproj -c Release -o ./publish -p:PublishSingleFile=false -p:SelfContained=false -p:UseAppHost=false


      # 2) Escribe web.config OUT OF PROCESS con la DLL correcta
      - name: Ensure logs dir
        shell: pwsh
        run: New-Item -ItemType Directory -Force -Path publish\logs | Out-Null


      # 3) WebDeploy con limpieza de destino
      - name: Deploy to WebDeploy (nestorvillca-001-site4)
        uses: jahbenjah/SmarterASP.NET-web-deploy@1.0.0.alpha.8
        with:
          website-name: nestorvillca-001-site4
          server-computer-name: https://win1031.site4now.net:8172/MsDeploy.axd
          server-username: ${{ secrets.SERVER_USERNAME }}   # debe ser: nestorvillca-001
          server-password: ${{ secrets.SERVER_PASSWORD }}   # contraseña de WebDeploy (VS WebDeploy -> Modify/Password)
          source-path: 'publish'
          target-delete: true
          additional-args: '-enableRule:AppOffline'
