# name: Deploy to MonsterASP.NET via FTP

# on:
#   push:
#     branches:
#       - master 

# jobs:
#   build_and_deploy:
#     runs-on: windows-latest
#     steps:
#       - uses: actions/checkout@v4

#       - name: Setup .NET 8
#         uses: actions/setup-dotnet@v3
#         with:
#           dotnet-version: 8.0

#       - name: Install dependencies
#         run: dotnet restore

#       - name: Build and Publish Project
#         run: dotnet publish -c Release -o ./publish

#       - name: Deploy to MonsterASP.NET via FTP
#         uses: SamKirkland/FTP-Deploy-Action@v4.3.5 
#         with:
#           server: site33967.siteasp.net          
#           username: site33967                  
#           password: ${{ secrets.MONSTERASP_FTP_PASSWORD }}  
#           port: 21                              
#           protocol: ftp                         
#           local-dir: ./publish/                  
#           server-dir: /wwwroot/                 
#           dangerous-clean-slate: false         

#       - name: ✅ Éxito
#         if: success()
#         run: echo "✅ Despliegue completado exitosamente."

#       - name: ❌ Error
#         if: failure()
#         run: echo "❌ Falló el build o el deploy. Revisa los logs en Actions."

name: Build & WebDeploy Backend (.NET 8)

on:
  push:
    branches: [ master, main ]
  workflow_dispatch: {}

jobs:
  build_and_deploy_backend:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore

      - name: Publish backend (Release, framework-dependent)
        run: |
          dotnet publish .\Autentication\Autentication.Web.csproj -c Release -o .\publish `
            -p:PublishSingleFile=false -p:SelfContained=false -p:UseAppHost=false
          mkdir publish\logs

      # Despliegue con limpieza del destino
      - name: Deploy to SmarterASP via WebDeploy (clean)
        uses: jahbenjah/SmarterASP.NET-web-deploy@1.0.0.alpha.8
        with:
          website-name: nestorvillca-001-site4
          server-computer-name: https://win1031.site4now.net:8172/MsDeploy.axd
          server-username: ${{ secrets.SERVER_USERNAME }}
          server-password: ${{ secrets.SERVER_PASSWORD }}
          source-path: 'publish'
          target-delete: true              # <- borra el destino antes de copiar
          additional-args: '-enableRule:AppOffline'  # evita locks
